FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore BeautyBooking.BlazorWasm/BeautyBooking.BlazorWasm.csproj
RUN dotnet publish BeautyBooking.BlazorWasm/BeautyBooking.BlazorWasm.csproj -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html

COPY --from=build /app/publish/wwwroot .

EXPOSE 80